language: php
php:
  - 5.6
  - 7.2
  - 7.3
  - 7.4

jobs:
  fast_finish: true

install:
  - composer install --prefer-dist --no-interaction

before_script:
  - echo 'phar.readonly = Off' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
